import type { NextPage } from 'next';
import Head from 'next/head';
import '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className='container grid grid-cols-6 gap-4 grid-rows-4'>
      <Head>
        <title>COSMO - 코딩 스터디 모임</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@400;500;700&display=swap'
          rel='stylesheet'
        />
      </Head>

      <header className='col-span-6'>
        <h1>COSMO</h1>
        <button>모집하기</button>
        <button>로그인</button>
      </header>

      <nav className='col-start-2 col-span-6'>
        <h2>카테고리별 커뮤니티</h2>
        <h3>커뮤니티 형태</h3>
        <h3>지역 및 동네</h3>
        <h3>기술 스택</h3>
        <h3>프로젝트 기간</h3>
      </nav>

      <main className='col-start-2 col-span-6'>
        main
        <section>
          section
          <article>article</article>
        </section>
      </main>

      <footer className='col-span-6'>footer</footer>
    </div>
  );
};

export default Home;
